### PR TITLE
Move OpenSSL iv_len conditional gem dependency

### PR DESCRIPTION
**Pull request by mt-clearhaus**
Fixes this issue on Debian Stretch:

```
root@ad648e4d0b64:/from-host# bundle install
[...]
[!] There was an error parsing `Gemfile`: 
[!] There was an error while loading `pedicel.gemspec`: Illformed requirement [{:git=>"https://github.com/clearhaus/aes256gcm_decrypt"}]. Bundler cannot continue.

 #  from /from-host/pedicel.gemspec:13
 #  -------------------------------------------
 #    unless OpenSSL::Cipher.new('aes-256-gcm').respond_to?(:iv_len=)
 >      s.add_runtime_dependency 'aes256gcm_decrypt', git: 'https://github.com/clearhaus/aes256gcm_decrypt'
 #    end
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /from-host/Gemfile:2
 #  -------------------------------------------
 #  source 'https://rubygems.org'
 >  gemspec
 #  -------------------------------------------
```

It seems e.g. a git path is not supported in a .gemspec file:

https://stackoverflow.com/questions/19494295/specify-git-path-in-gemspec-add-dependency-entry

### CODE REVIEW

**Comment by ct-clearhaus** [comment]
If we publish `aes256gcm_decrypt` as a gem, would it be better to keep the `add_runtime_dependency` or move it to the Gemfile?

**Comment by mt-clearhaus** [comment]
I am not experienced in managing Ruby dependencies, but having the dependencies in one place (the .gemspec file) appeals to me. [aes256gcm_decrypt](https://github.com/clearhaus/aes256gcm_decrypt) has a "thin" [Gemfile](https://github.com/clearhaus/aes256gcm_decrypt/blob/b2a2979369a8b9843cd55e58cc26f1d40c86de0c/Gemfile) and all dependencies in [aes256gcm_decrypt.gemspec](https://github.com/clearhaus/aes256gcm_decrypt/blob/b2a2979369a8b9843cd55e58cc26f1d40c86de0c/aes256gcm_decrypt.gemspec#L12-L13).

**Comment by mt-clearhaus** [comment]
I have pushed the gem to rubygems.org: https://rubygems.org/gems/aes256gcm_decrypt

**Comment by mt-clearhaus** [comment]
@ct-clearhaus It seems a bit of polishing is in order... https://github.com/clearhaus/aes256gcm_decrypt/pull/10

**Comment by ct-clearhaus** [comment]
FYI: debian stretch with `ruby` and `bundler` installed, `bundle install` yields
```
compiling aes256gcm_decrypt.c
aes256gcm_decrypt.c:5:25: fatal error: openssl/evp.h: No such file or directory
 #include <openssl/evp.h>
```

`/usr/include/openssl/evp.h` is coming from `libssl-dev`.

**Comment by mt-clearhaus** [comment]
Version 0.0.2 of `aes256gcm_decrypt` has been pushed: https://rubygems.org/gems/aes256gcm_decrypt

**Review by ct-clearhaus — APPROVED** [review]
👍

**Pull request merged**
