### PR TITLE
Validate token on initialization

### PR DESCRIPTION
**Pull request by ct-clearhaus**
I think the user shouldn't validate the token explicitly. @mt-clearhaus WDYT?

Specs ...

### CODE REVIEW

**Comment by kse-clearhaus** [comment]
This makes sense :+1:.
Now there's just the matter of failing tests. :)

**Comment by mt-clearhaus** [comment]
@ct-clearhaus explains to me that it indeed is relevant that the configuration cannot be changed later, when validation of the token takes place on initialization. Otherwise the certificate in the configuration can be changed, making the initial validation pointless.

I like this :slightly_smiling_face: :+1:

**Comment by ct-clearhaus** [comment]
The specs are now good, but, well ... @kse-clearhaus @mt-clearhaus 👀

**Review by mt-clearhaus — APPROVED** [review]
LGTM :+1:

**Pull request merged**
