### PR TITLE
Remove dependence on aes256gcm_decrypt, thus now making it compatible with Ruby 2.5.5.

### PR DESCRIPTION
**Pull request by kbadk**

### CODE REVIEW

**Comment by kbadk** [comment]
Of course the build pipeline has been broken. I guess I'll also migrate CircleCI to GitHub Actions in this PR.

**Comment by kbadk** [comment]
Notice that the current build error is simply [CircleCI complaining about the lack of a config file](https://app.circleci.com/pipelines/github/clearhaus/pedicel). This will go away once a CircleCi admin [clicks "Stop building" on this project](https://app.circleci.com/settings/project/github/clearhaus/pedicel) (@ct-clearhaus?).

**Comment by ct-clearhaus** [comment]
CircleCI: "Stop building" ✅

**Review by ct-clearhaus — APPROVED** [review]
Awesome!

I think I remember that I tried to have the same gemspec work for both 2.3 and 2.5, but failed on this and thus discarded the 2.5 stuff back then. If somebody cares for patching 2.3 in case some security issue is uncovered, then we may want to track 2.3 in a separate branch, or fork, or ...?

So, perhaps we should with this PR also announce that support for Ruby 2.3 is not maintained anymore?

**Comment by kbadk** [comment]
I think publishing a new package to rubygems.org will suffice in terms of announcements.

**Pull request merged**
