### PR TITLE
Remove support for shared_secret

### PR DESCRIPTION
**Pull request by ct-clearhaus**
As requested by @mt-clearhaus: https://github.com/clearhaus/pedicel/pull/7#discussion_r188629788

### CODE REVIEW

**Comment by mt-clearhaus** [comment]
Honestly, I did not grasp that I requested that :slightly_smiling_face:

**Comment by mt-clearhaus** [comment]
Perhaps it is superfluous to raise an `ArgumentError` in line 71 due to a malformatted `shared_secret`, as the `shared_secret` is always produced by the `shared_secret` method (called in line 41)? The generation of the secret ought to complain if it could not construct a correct secret from the given private key.

https://github.com/clearhaus/pedicel/blob/d70d849f0e5757e0cbcad0f05a1c613ab9950adc/lib/pedicel/ec.rb#L69-L71

If yes, the spec https://github.com/clearhaus/pedicel/blob/d70d849f0e5757e0cbcad0f05a1c613ab9950adc/spec/lib/pedicel/ec_spec.rb#L218-L220 can also be removed.

Other than this, I like what I see in the PR.

**Comment by ct-clearhaus** [comment]
> (...) as the `shared_secret` is always produced by the `shared_secret` method (called in line 41)?

Nope, `Pedicel::EC.symmetric_key` is public, so users can (and we do this in the specs) call `Pedicel::EC.symmtric_key` with `shared_secret`.

**Review by mt-clearhaus — APPROVED** [review]
:+1:

**Pull request merged**
